### ISSUE TITLE
Merge is not a function

### ISSUE THREAD

**Issue by thierryskoda** [Volst/graphql-form-helpers#7]
I'm using **create-react-app** and it looks like there's an error with `deepmerge` library

I think this is related to this: https://github.com/KyleAMathews/deepmerge/issues/97

I copied the dist folder into my repo and tried the fix where it says to do `const merge = require('deepmerge').default` and it works but I don't think it's the best!

I'm not a webpack expert too so I'm not sure of the solution...

If anyone thinks of the solution of this I would be so happy.

Really nice library!!

Thank you 
Thierry

**Comment by SpaceK33z** [comment]
Thanks for your bug report! The issue should be fixed now :). Also please let me know if you have any tips to improve this package!

**Comment by thierryskoda** [comment]
Thank you for fixing it so quickly! 

Yes, I have some questions. I will create another issue for it if that's okay.
